#+OPTIONS: toc:nil num:nil

* Introduction

Knowledge is understanding or awareness of facts and information that /we know/; however, I think knowledge should be defined as understanding or awareness of information that /we do not know/!  

You might ask why? In our time information is abundant! You could easily and  quickly find out about an idea, method, information or a skill. However, it takes time to master the field--understand its boundaries and limitation. It takes an expert to find unanswered questions, understand, and measure them! Thus, having knowledge translates into the awareness of questions that are unanswered or unknown!

This should actually be the practice in the scientific community! Finding, understanding, and /measuring/ what unanswered questions are. Why do we need measurement, you might ask. We require measurement to have progress. Understanding the boundaries of a unknown (measuring the unknown) is the first step in understanding. We should measure the unknown to tackle it and proceed. I call this process *Ignometry* (ignotus=unknown, metry=measuring, measuring the unknown). 

I believe, in our schools, professors should teach the students what we do not know at least beside what we already know. Have you ever seen a professor coming to a class and tell you: here are the things we don't know in the area! or here are questions that are still unanswered! I believe it creates much excitement and motivation in the fresh minds of students. 

The same story goes into research community! There is no clear picture--a map for the unknowns. I keep asking myself: what are open questions in our field? What problems we don't still have a clear answer for? What do we know about them? Which ones are we able to tackle with our current knowledge? I believe everyone should devote a potion of his/her own time to *Ignometry* and then pass this torch forward. This will exponentially increase our progress and pace in science! Everyweek I am expending an afternoon on *Ignometry* and try to understand the boundries of the unknown!


